services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      # Mount to conf.d, NOT directly to nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  app:
    image: dmandevv/todo-api:latest  # Use the image pushed to Docker Hub
    environment:
    - MONGO_URI=mongodb://mongodb:27017/todoapp
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: